adboard/urls.py
from django.conf.urls import url
from django.contrib import admin
from board import views
from django.core.files import File
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', views.home_page, name='home_page'),
    url(r'^ads/add/$', views.add_advertisement, name='add_adv'),
    url(r'^login/$', views.login_usr, name='usr_login'),
    url(r'^ads/(?P<id>[0-9]*)/$', views.ad_show, name="show_ad"),  
    url(r'^contacts/', views.contact_page, name='contact_page'), 
    url(r'^registration/', views.usr_registration, name='registration_page'),
    url(r'^ad_new/', views.ad_new, name='ad_new'),
    url(r'^profile/', views.my_profile, name='my_profile'),
    url(r'^logout/$', views.logout_view, name='logout'),
    # url(r'^ad_show_submit/', views.ad_show_submit, name='ad_show_submit')
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

board/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _
from django.db import models
from unidecode import unidecode
from django.template.defaultfilters import slugify
from multiselectfield import MultiSelectField
import datetime
from django.core.files.storage import FileSystemStorage
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

# Create your models here.
class Category(models.Model):
	  name = models.TextField( _(u'название'), max_length=255)
	  slug = models.SlugField(max_length=50, unique=True, blank=True, default=None, null=True)
	  
	  def __unicode__(self):
	  	  return unicode(self.name)
	  
	  def save(self):
	      self.slug = slugify(unidecode(self.name))
	      super(Category, self).save()

	  class Meta:
		    verbose_name = _(u'Категория')
		    verbose_name_plural = _(u'Категории')

class Subcategory(models.Model):
	  name = models.TextField( _(u'Название'), max_length=255)
	  category = models.ForeignKey(Category, related_name='subcategories', on_delete=models.CASCADE)
	  parentId = models.ForeignKey("self", related_name='children',default=None, blank=True, null=True)
	  slug = models.SlugField(max_length=50, unique=True, blank=True, default=None, null=True)

	  def __unicode__(self):
	  	  return unicode(self.name)
	  
	  def save(self):
	      self.slug = slugify(unidecode(self.name))
	      super(Subcategory, self).save()

	  class Meta:
		    verbose_name = _(u'Подкатегория')
		    verbose_name_plural = _(u'Подкатегории')

# class Document(models.Model):
#     description = models.CharField(max_length=255, blank=True)
#     image = models.ImageField(upload_to='images/')
#     uploaded_at = models.DateTimeField(auto_now_add=True)

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
  

@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)

@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    if hasattr(instance, 'profile'):
        instance.profile.save()


class Advertisement(models.Model):
	  ALL_KG = 'All_Kyrgyzstan'
	  ALA_BUKA = 'Ala_Buka'
	  ANANEVO = 'Ananevo'
	  ARAVAN = 'Aravan'
	  AT_BASHI = 'At_Bashi'
	  BAET = 'Baet'
	  BAETOV = 'Baetov'
	  BAZAR_KORGON = 'Bazar_Korgon'
	  BAKAY_ATA = 'Bakay_Ata'
	  BAKTUU_DOLONOTU = 'Baktuu dolonotu'
	  BALYIKCHI = 'Balyikchi'
	  BATKEN = 'Batken'
	  BELOVODSKOE = 'Belovodskoe'
	  BISHKEK = 'Bishkek'
	  BOKONBAEVO = 'Bokonbaevo'
	  BOSTERI = 'Bosteri'
	  GRIGOREVKA = 'Grigorevka'
	  GULCHA = 'Gulcha'
	  DAROOT_KORGON = 'Daroot_Korgon'
	  DZHALAL_ABAD = 'Dzhalal_Abad'
	  ZHARKYINBAEV = 'Zharkyinbaev'
	  ISFANA = 'Isfana'
	  KAZARMAN = 'Kazarman'
	  KAINDYI = 'Kaindyi'
	  KANISH_KIYA = 'Kanish_Kiya'
	  KANT = 'Kant'
	  KARA_BALTA = 'Kara_Balta'
	  KARAKOL = 'Karakol'
	  KARA_KUL = 'Kara_kul'
	  KARA_KULDZHA = 'Kara_Kuldzha'
	  KARA_OY = 'Kara_Oy'
	  KARA_SUU = 'Kara_Suu'
	  KASHAT = 'Kashat'
	  KEMIN = 'Kemin'
	  KERBEN = 'Kerben'
	  KOZHOYAR = 'Kozhoyar'
	  KOK_OY = 'Kok_Oy'
	  KORUMDU = 'Korumdu'
	  KOCHKOR = 'Kochkor'
	  KYIZYIL_ADYIR = 'Kyizyil_Adyir'
	  KYIZYIL_KIYA = 'Kyizyil_Kiya'
	  KYIZYIL_SUU = 'Kyizyil_Suu'
	  LEBEDINOVKA = 'Lebedinovka'
	  MASSYI = 'Massyi'
	  NARYIN = 'Naryin'
	  NOOKAT = 'Nookat'
	  ORTO_ORUKTU = 'Orto_Oruktu'
	  OSH = 'Osh'
	  POKROVKA = 'Pokrovka'
	  PULGON = 'Pulgon'
	  SEMENOVKA = 'Semenovka'
	  SOKULUK = 'Sokuluk'
	  SUZAK = 'Suzak'
	  SULYUKTA = 'Sulyukta'
	  TALAS = 'Talas'
	  TAMCHYI = 'Tamchyi'
	  TEMIR = 'Temir'
	  TEPLOKLYUCHENKA = 'Teploklyuchenka'
	  TOKMAK = 'Tokmak'
	  TOKTOGUL = 'Toktogul'
	  TYUP = 'Tyup'
	  UZGEN = 'Uzgen'
	  CHAEK = 'Chaek'
	  CHOK_TAL = 'Chok_Tal'
	  CHOLPON_ATA = 'Cholpon_Ata'
	  CHON_SARYI_OY = 'Chon_Saryi_Oy'
	  SHOPOKOV = 'Shopokov'

	  LOCATIONS = (
	  	(ALL_KG,'Весь Кыргызстан'), (ALA_BUKA,'Ала-Бука'),	(ANANEVO,'Ананьево'),	(ARAVAN,'Араван'),	(AT_BASHI,'Ат-Баши'),	(BAET,'Бает'),	(BAETOV,'Баетов'),	(BAZAR_KORGON,'Базар-Коргон'),	(BAKAY_ATA,'Бакай-Ата'),	(BAKTUU_DOLONOTU,'Бактуу долоноту'),	(BALYIKCHI,'Балыкчи'),	(BATKEN,'Баткен'),	(BELOVODSKOE,'Беловодское'),	(BISHKEK,'Бишкек'),	(BOKONBAEVO,'Боконбаево'),	(BOSTERI,'Бостери'),	(GRIGOREVKA,'Григорьевка'),	(GULCHA,'Гульча'),	(DAROOT_KORGON,'Дароот-Коргон'),	(DZHALAL_ABAD,'Джалал-Абад'),	(ZHARKYINBAEV,'Жаркынбаев'),	(ISFANA,'Исфана'),	(KAZARMAN,'Казарман'),	(KAINDYI,'Каинды'),	(KANISH_KIYA,'Каниш-Кия'),	(KANT,'Кант'),	(KARA_BALTA,'Кара-Балта'),	(KARAKOL,'Каракол'),	(KARA_KUL,'Кара-куль'),	(KARA_KULDZHA,'Кара-Кульджа'),	(KARA_OY,'Кара-Ой'),	(KARA_SUU,'Кара-Суу'),	(KASHAT,'Кашат'),	(KEMIN,'Кемин'),	(KERBEN,'Кербен'),	(KOZHOYAR,'Кожояр'),	(KOK_OY,'Кок-Ой'),	(KORUMDU,'Корумду'),	(KOCHKOR,'Кочкор'),	(KYIZYIL_ADYIR,'Кызыл-Адыр'),	(KYIZYIL_KIYA,'Кызыл-Кия'),	(KYIZYIL_SUU,'Кызыл-Суу'),	(LEBEDINOVKA,'Лебединовка'),	(MASSYI,'Массы'),	(NARYIN,'Нарын'),	(NOOKAT,'Ноокат'),	(ORTO_ORUKTU,'Орто-Орукту'),	(OSH,'Ош'),	(POKROVKA,'Покровка'),	(PULGON,'Пульгон'),	(SEMENOVKA,'Семеновка'),	(SOKULUK,'Сокулук'),	(SUZAK,'Сузак'),	(SULYUKTA,'Сулюкта'),	(TALAS,'Талас'),	(TAMCHYI,'Тамчы'),	(TEMIR,'Темир'),	(TEPLOKLYUCHENKA,'Теплоключенка'),	(TOKMAK,'Токмак'),	(TOKTOGUL,'Токтогул'),	(TYUP,'Тюп'),	(UZGEN,'Узген'),	(CHAEK,'Чаек'),	(CHOK_TAL,'Чок-Тал'),	(CHOLPON_ATA,'Чолпон-Ата'),	(CHON_SARYI_OY,'Чон-Сары-Ой'),	(SHOPOKOV,'Шопоков'),
	 	)


	  KGS = "KGS"
	  USD = "USD"
	  UNITS = (
	    (KGS,'KGS'),	(USD,'USD')
	  )

	  location = models.CharField(_(u'Местоположение'), max_length=30, choices = LOCATIONS, default = BISHKEK)
	  category = models.ForeignKey(Category, on_delete=models.CASCADE)
	  subcategory = models.ForeignKey(Subcategory, on_delete=models.CASCADE)
	  title = models.CharField(_(u'Заголовок'), max_length=255, null=False)
	  description = models.TextField(_(u'Описание'), max_length=2048, null=False)
	  price = models.CharField(_(u'Цена'), max_length=100, default="Договорная", blank=True, null=True)
	  unit = models.CharField(_(u'Валюта'), max_length=10, choices = UNITS, default = KGS)
	  # create_date = models.DateTimeField(default=None, blank=True, null=True)
	  create_date = models.DateTimeField(auto_now_add=True)
	  author = models.ForeignKey(Profile, on_delete=models.CASCADE)
	  # image = models.ImageField(upload_to='images/')

	  def save(self):
	  		self.create_date = datetime.datetime.now()
	  		super(Advertisement, self).save()		

	  class Meta:
		  	verbose_name = _(u'Объявление')
		  	verbose_name_plural = _(u'Объявления')


class AdImage(models.Model):
		file = models.FileField(upload_to='board_images/', default='/static/board/images/images.png')
		uploaded_at = models.DateTimeField(auto_now_add=True )
		advertisement = models.ForeignKey(Advertisement, related_name='images', on_delete = models.CASCADE)


class Comment(models.Model):
	  adv = models.ForeignKey(Advertisement, on_delete=models.CASCADE)
	  comment = models.TextField(_(u'Комментарий'), max_length=1024, null=False)


class Discount(models.Model):  
	  title = models.CharField(_(u'Название'), max_length=255, null=False)
	  price = models.CharField(_(u'Цена или скидка'), max_length=100, default="Договорная", blank=True, null=True)
	  # create_date = models.DateTimeField(default=None, blank=True, null=True)
	  date_to = models.DateTimeField(_(u'Дата истечения скидки'), blank=True, null=True)
	  link = models.CharField(_(u'Ссылка'), max_length=300, blank=True, null=True)
	  # image = models.ImageField(upload_to='images/')

	  def save(self):
	  		self.create_date = datetime.datetime.now()
	  		super(Discount, self).save()		

	  class Meta:
		  	verbose_name = _(u'Скидка')
		  	verbose_name_plural = _(u'Скидки')

class News(models.Model):  
	  title = models.CharField(_(u'Название'), max_length=255, null=False)
	  description = models.TextField(_(u'Описание'), max_length=4096, null=False)
	  create_date = models.DateTimeField(auto_now_add=True)
	  # image = models.ImageField(upload_to='images/')

	  def save(self):
	  		super(News, self).save()		

	  class Meta:
		  	verbose_name = _(u'Новость')
		  	verbose_name_plural = _(u'Новости')

board/forms.py
# -*- coding: utf-8 -*-

from django import forms
from .models import Advertisement, AdImage, Comment
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class AdvertisementForm(forms.ModelForm):

    class Meta:
        model = Advertisement
        fields = ('location', 'category', 'subcategory', 'title', 'description', 'price', 'unit', )

class ImageForm(forms.ModelForm):
    file = forms.FileField(label='')

    class Meta:
        model = AdImage
        fields = ('file', )

class SignUpForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2', )


class CommentForm(forms.ModelForm):
    comment =  forms.CharField ( widget=forms.widgets.Textarea() )

    class Meta():
    	model = Comment
    	fields = ()

board/views.py
from board.models import *
from collections import defaultdict
import datetime
from django.shortcuts import render, redirect, get_object_or_404
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from .forms import AdvertisementForm, ImageForm, SignUpForm, CommentForm
from django.db import transaction
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.forms import modelformset_factory


def home_page(request):
    ads = Advertisement.objects.all()
    categories = Category.objects.all()
    subcategories = Subcategory.objects.all()
    subcategories_grouped = defaultdict(list)
    # images = AdImage.objects.all()
    # for im in images:
    #     print im.advertisement.pk
    #     print im.file.url

    for subcategory in subcategories:
        subcategories_grouped[subcategory.category_id].append(subcategory)
        
    subcategories_by_category= dict(subcategories_grouped)

    discounts = Discount.objects.all()

    return render(request, 'board/home.html', {'ads': ads, 'categories': categories, 'subcategories_by_category': subcategories_by_category, 'discounts': discounts})


def ad_show(request, id):
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.save()
            id= form.cleaned_data['adv']
            ad = get_object_or_404(Advertisement.objects, pk = id)
            return redirect(ad)
    else:
        ad = get_object_or_404(Advertisement.objects, pk = id)
        comments = Comment.objects.filter(adv_id= ad.id)
        comment_form = CommentForm()
    return render(request, 'board/ad_show.html', {'ad': ad, 'comments': comments, 'form': comment_form})


def contact_page(request):
    return render(request, 'board/contacts.html')


def ad_new(request):
    return render(request, 'board/ad_new.html')

@login_required(login_url='/login/')
def add_advertisement(request):
    ImageFormSet = modelformset_factory(AdImage, form=ImageForm)
    if request.method == "POST":
        adv_form = AdvertisementForm(request.POST, prefix='adv' )
        formset = ImageFormSet(request.POST, request.FILES,
                                       queryset=AdImage.objects.none())
        # image_form = ImageForm(request.POST, request.FILES, prefix='img' )
        if adv_form.is_valid() and formset.is_valid() :
            adv = adv_form.save(commit=False)
            adv.author = request.user.profile
            adv.save()
            for form in formset.cleaned_data:
                          file = form['file']
                          image = AdImage(advertisement=adv, file=file)
                          image.save()
            return redirect('my_profile')
    else:
        adv_form = AdvertisementForm(prefix='adv')
        formset = ImageFormSet(queryset=AdImage.objects.none())
        # image_form = ImageForm(prefix='img')
    return render(request, 'board/adv_add.html', {'adv_form': adv_form, 'formset': formset })

@login_required(login_url='/login/')
def edit_adv(request, pk):
    adv = get_object_or_404(Advertisement, pk=pk)
    if request.method == "POST":
        adv_form = AdvertisementForm(request.POST, prefix='adv', instance=adv )
        image_form = ImageForm(request.POST, request.FILES, prefix='img' )
        if adv_form.is_valid() and image_form.is_valid() :
            adv = form.save(commit=False)
            adv.save()
            return redirect('profile')
    else:
        adv_form = AdvertisementForm(request.POST, prefix='adv', instance=adv )
        image_form = ImageForm(request.POST, request.FILES, prefix='img' )
    return render(request, 'board/adv_edit.html', {'adv_form': adv_form, 'image_form': image_form })

def usr_registration(request):
    if request.method == 'POST':
        user_form = SignUpForm(request.POST)
        if user_form.is_valid():
            user = user_form.save()
          
            raw_password = user_form.cleaned_data.get('password1')
            user_ = authenticate(username=user.username, password=raw_password)
            login(request, user_)
            return redirect('home_page')
        else:
            errors = user_form.errors
            return render(request, 'board/registration.html', {
         'errors':  errors,      
        'user_form': user_form
    })

    else:
        user_form = SignUpForm()

    return render(request, 'board/registration.html', {
        'user_form': user_form
    })


def login_usr(request):
    # if request.user.is_authenticated:
    #     # return redirect('board_index')
    #     return render(request, 'board/board_index.html', {})
    # else:
        logout(request)
        # pdb.set_trace()
        username = password = ''
        if request.POST:
            username = request.POST['username']
            password = request.POST['password']

            user = authenticate(username=username, password=password)
            if user is not None:
                if user.is_active:
                    login(request, user)
                    return redirect('home_page')
        return render(request, 'board/login_usr.html', {})


@login_required(login_url='/login/')
def my_profile(request):
    # ads = Advertisement.objects.all()
    categories = Category.objects.all()
    subcategories = Subcategory.objects.all()
    # user = Profile.objects.all()
    subcategories_grouped = defaultdict(list)

    for subcategory in subcategories:
        subcategories_grouped[subcategory.category_id].append(subcategory)
        
    subcategories_by_category= dict(subcategories_grouped)

    my_ads = Advertisement.objects.filter(author = request.user.profile)
    return render(request, 'board/my_profile.html', { 'categories': categories, 'subcategories_by_category': subcategories_by_category, 'user': 0, 'my_ads': my_ads})


def logout_view(request):
    logout(request)
    return redirect('home_page')

board/templates/board/ad_show.html
{% extends "board/base.html" %}
{% block title %}{{ad.title}}{% endblock %}
{% load static %}
{% block content %}
	<div class="page-content">
		<div class="container">
			<div class="ad-content">
				<div class="row">
					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
						<div class="title"><h2>{{ad.title}}</h2> </div>
						
					</div>
					<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">
						<div class="image">
							<div class="item">
								<div class="clearfix" style="">
									<ul id="image-gallery" class="gallery list-unstyled cS-hidden">
										  {% for img in ad.images.all %}
											<li data-thumb="{{ img.file.url }}">
												<img src="{{ img.file.url }}" />
											</li>
											{% endfor %}
											<!-- {% for im in images %} -->
										<!-- {% endfor %} -->
										<!-- <li data-thumb="{% static 'board/images/main.png' %}" >
											<img src="{% static 'board/images/main.png' %}" />
										</li>
										<li data-thumb="{% static 'board/images/fon-51.gif' %}" >
											<img src="{% static 'board/images/fon-51.gif' %}" />
										</li>
										<li data-thumb="{% static 'board/images/fon-51.gif' %}" >
											<img src="{% static 'board/images/fon-51.gif' %}" />
										</li>
										<li data-thumb="{% static 'board/images/index.jpg' %}" >
											<img src="{% static 'board/images/index.jpg' %}" />
										</li> -->
									</ul>
								</div>
							</div>
						</div>
						<div class="price">
							<div class="field-name">Цена:  </div>
							<div class="price-inf"><button class="priceBtn" type="">
								<span class="count">{{ad.price}}</span>
								<span class="unit">{{ad.unit}}</span></button></div>
							</div>
							<div class="row ad-info">
								<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
									<div class="category"><div class="field-name">Категория:  </div>  {{ad.category}} </div>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
									<div class="createddate"><div class="field-name">Дата объявления:  </div>{{ad.create_date}}</div>
								</div>
								<div class="col-lg-6 col-md-6 col-sm-6 col-xs-12">
									<div class="loc"><div class="field-name">Город:  </div>{{ad.get_location_display}} </div>
								</div>
							</div>
							<div class="desc">{{ad.description}} </div>
							<!-- </div> -->
							
						</div>
						<div class="col-lg-4 col-md-4 col-sm-12 col-xs-12">
							<div class="seller">
								<h4>Информация о продавце</h4>
								<div class="name"><div class="field-name">Продавец: </div> <a href="">{{ad.author.user}}</a></div>
								<div class="phone"><div class="field-name">Позвонить:  </div> <a href="tel:+0894105874"><button type="" class="phoneBtn">+0894105874</button></a></div>
							</div>
						</div>
						
						<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
							<h3>Добавить комментарий</h3>
							
							<button type=""></button>
							<form action="/ads/{{ad.id}}/" method="post" accept-charset="utf-8">
								{% csrf_token %}
								{% if next %}
									<input type="hidden" name="next" value="{{ next }}" />
								{% endif %}
								<input type="hidden"  name="adv" id="adv" value="{{ad.id}}">
								<textarea name="comment"></textarea>
								<input type="submit" name="" value="добавить коммент">
							</form>
							<h3>Комментарии</h3>
						</div>
					</div>
				</div>
			</div>
		</div>
	{% endblock %}

board/templates/board/contacts.html
{% extends "board/base.html" %}
{% block title %}Контакты{% endblock %}
{% load static %}
{% block content %}
	<div class="page-content">
		<div class="container">
			<div class="contact-container">
				<div class="phones"><div class="field-name">Телефоны:  </div> +996 701 01 71 16, +996 700 01 66 61</div>
				<div class="phones"><div class="field-name">Whatsapp:</div> +996 700 01 66 61</div>
				<div class="phones"><div class="field-name">Skype:</div> lolopepe.kg</div>
				<div class="phones"><div class="field-name">E-mail: </div> lolopepe.kg@mail.ru</div>
				<div class="phones"><div class="field-name">Адрес: </div> Горького / Бектенова 10, 2 этаж, 12 кабинет</div>
				<div class="phones"><div class="field-name">Время работы: </div> Пн-Сб 09:00–17:00</div>
			</div>
		</div>
	</div>
{% endblock %}

board/templates/board/home.html
{% extends "board/base.html" %}
{% block title %}Главная | Доска объявлений{% endblock %}
{% load static %}
{% block content %}
	<div class="page-content">
		<div class="container">
			<div class="categories-nav">
				{% for category in categories %}
					<div class="menu-{{category.slug}} dropdown-categories">
						<a href="#" class="category-link">
							<div class="category-image">
								<img src="{% static 'board/images/'|add:category.slug|add:'.png' %}" alt="">
							</div>
							<div class="category-name">{{category.name}}
							</div>
						</a>
						<div class="dropdown-content">
							{% for subcategory in subcategories_by_category|get_item:category.id %}
								<a href="#">{{subcategory.name}}</a>
								<ul>
									
								</ul>
							{% endfor %}
						</div>
					</div>
				{% endfor %}
			</div>
			<div class="mobile-categ">
				{% for category in categories %}
					<div class="mobile-{{category.slug}} mobile-dropdown-categories">
						<a href="#" class="category-link">
							<div class="mobile-category-image">
								<img src="{% static 'board/images/'|add:category.slug|add:'.png' %}" alt="">
							</div>
							<div class="mobile-category-name">{{category.name}}
							</div>
						</a>
						<div class="mobile-dropdown-content">
							<ul class="cat-list">
								{% for subcategory in subcategories_by_category|get_item:category.id %}
									<a href="#"><li>{{subcategory.name}}</li></a>
								{% endfor %}
							</ul>
						</div>
					</div>
				{% endfor %}
			</div>
			<div class="new-ad">
				<a href="{% url 'add_adv'%}">
					<button type="" class="buttonNewAd">Подать объявление</button>
				</a>
			</div>
			
			
			
			<div class="content">
			
				<div class="fullwidth">
					<div class="row">
						<div class="col-lg-9 col-md-9 col-sm-9 col-xs-12">
							<h3>Новые объявления</h3>
							
							{% for ad in ads %}
								<div class="board_item">
									<div class="row">
										
										<div class="col-lg-3 col-md-3 col-sm-4 col-xs-4">
											<a href="{% url 'show_ad' id=ad.id %}">
												<div class="image"><img src="{{ ad.images.all.0.file.url }}" alt=""></div>
											</a>
										</div>
										<div class="col-lg-9 col-md-9 col-sm-8 col-xs-8">
											<a href="{% url 'show_ad' id=ad.id %}">
												<div class="title"><h4>{{ad.title}}</h4> </div>													</a>
												<div class="category">{{ad.category}} </div>
												<div class="createddate">{{ad.create_date}}</div>
												<div class="author"><a href="">{{ad.author.user}}</a></div>
												<div class="price"><span class="count">{{ad.price}}</span>
												<span class="unit">{{ad.unit}}</span></div>
												<div class="loc">{{ad.get_location_display}} </div>
											</div>
										</div>
									</div>
								{% endfor %}
								
							</div>
							<div class="col-lg-3 col-md-3 col-sm-3 col-xs-12">
								<h3>Скидки и Акции</h3>
								{% for discount in discounts %}
									<div class="discount">
										<a href={{discount.link}}>
											<div class="image"><img src="{% static 'board/images/images.png' %}" alt=""></div>
											<div class="discount-info"><div class="title"><h4>{{discount.title}}</h4> </div>
											<div class="price"><h4>{{discount.price}}</h4></div>
											
											<!-- <div class="date_to">{{discount.date_to}}</div> -->
										</div>
									</a>
								</div>
							{% endfor %}
						</div>
					</div>
				</ul>
			</div>
			<div class="mobile-tabs">
				<div class="tabs">
					<input id="tab1" type="radio" name="tabs" checked>
					<label for="tab1" title="Объявления">Объявления</label>
					
					<input id="tab2" type="radio" name="tabs">
					<label for="tab2" title="Скидки">Скидки</label>
					
					<section id="content-tab1">
						<p>
							<h3>Новые объявления</h3>
							{% for ad in ads %}
								<div class="board_item">
									<div class="row">
										<div class="col-lg-3 col-md-3 col-sm-4 col-xs-4">
											<a href="{% url 'show_ad' id=ad.id %}">
												<div class="image"><img src="{% static 'board/images/images.png' %}" alt=""></div>
											</a>
										</div>
										<div class="col-lg-9 col-md-9 col-sm-8 col-xs-8">
											<a href="{% url 'show_ad' id=ad.id %}">
												<div class="title"><h4>{{ad.title}}</h4> </div>													</a>
												<div class="category">{{ad.category}} </div>
												<div class="createddate">{{ad.create_date}}</div>
												<div class="price"><span class="count">{{ad.price}}</span>
												<span class="unit">{{ad.unit}}</span></div>
												<div class="loc">{{ad.get_location_display}} </div>
											</div>
										</div>
									</div>
								{% endfor %}
							</p>
						</section>
						<section id="content-tab2">
							<p>

								<h3>Скидки и Акции</h3>
								<div class="row">
								{% for discount in discounts %}
									
										<div class="col-sm-6 col-xs-6">
											<div class="discount">
												<a href={{discount.link}}>
													<div class="image"><img src="{% static 'board/images/images.png' %}" alt=""></div>
													<div class="discount-info"><div class="title"><h4>{{discount.title}}</h4> </div>
													<div class="price"><h4>{{discount.price}}</h4></div>
													<!-- <div class="date_to">{{discount.date_to}}</div> -->
												</div>
											</a>
										</div>
									</div>
								
							{% endfor %}
							</div>
						</p>
						 </section>  
					</div>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}